services:
  - type: web
    name: visionflow-backend
    env: python
    plan: free
    region: oregon
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py
    workingDir: backend
    autoDeploy: true
